 /******************************************************************************
 File Name: cmsCreateTables.sql

 Purpose:
   This script is run as bard of the create database process.  it creates all
of the tables within the database

 Revision History

 Who     When           What
 ----    ----------     -------------------------------------------------------
 kwa     11.10.2015     created
 ******************************************************************************/

create table address (
  id bigint generated by default as identity,
  version bigint not null,
  apt_suite varchar(255) not null,
  attn varchar(255) not null,
  city varchar(255) not null,
  postal_code varchar(255) not null,
  state_id bigint not null,
  street varchar(255) not null,
  primary key (id)
);

create table appointment (
    id bigint generated by default as identity,
    version bigint not null,
    description varchar(255) not null,
    end_dte timestamp not null,
    firm_id bigint not null,
    organizer_id bigint not null,
    start_dte timestamp not null,
    primary key (id)
);

create table business_entity (
    id bigint generated by default as identity,
    version bigint not null,
    address_id bigint not null,
    primary key (id)
);

create table client (
    id bigint not null,
    company_name varchar(255) not null,
    primary key (id)
);

create table contact (
    id bigint not null,
    client_id bigint not null,
    legal_case_id bigint not null,
    primary key (id)
);

create table daily_log_entry (
    id bigint generated by default as identity,
    version bigint not null,
    employee_id bigint not null,
    hours_billed decimal(19,2) not null,
    legal_case_id bigint not null,
    log_dte timestamp not null,
    primary key (id)
);

create table email_address (
    id bigint generated by default as identity,
    version bigint not null,
    email_address varchar(255) not null,
    owner_id bigint not null,
    type_id bigint not null,
    primary key (id)
);

create table employee (
    id bigint not null,
    salary decimal(19,2) not null,
    primary key (id)
);

create table firm (
    id bigint not null,
    billable_hours decimal(19,2) not null,
    firm_name varchar(255) not null,
    lexus_nexus_url varchar(255) not null,
    primary key (id)
);

create table lawyer (
    id bigint not null,
    billing_rate decimal(19,2) not null,
    primary key (id)
);

create table lawyer_specialty (
    lawyer_id bigint not null,
    specialty_id bigint not null,
    primary key (lawyer_id, specialty_id)
);

create table legal_case (
    id bigint generated by default as identity,
    version bigint not null,
    begin_dte timestamp not null,
    client_id bigint not null,
    close_dte timestamp not null,
    description varchar(255) not null,
    end_dte timestamp not null,
    is_pro_bono boolean not null,
    primary_lawyer_id bigint not null,
    total_cost decimal(19,2) not null,
    primary key (id)
);

create table legal_case_employee (
    legal_case_id bigint not null,
    employee_id bigint not null,
    primary key (legal_case_id, employee_id)
);

create table person (
    id bigint not null,
    fname varchar(255) not null,
    lname varchar(255) not null,
    user_id varchar(255) not null,
    user_password varchar(255) not null,
    primary key (id)
);

create table person_appointment (
    person_id bigint not null,
    appointment_id bigint not null,
    primary key (person_id, appointment_id)
);

create table phone_number (
    id bigint generated by default as identity,
    version bigint not null,
    owner_id bigint not null,
    phone_number varchar(255) not null,
    type_id bigint not null,
    primary key (id)
);

create table specialty (
    id bigint generated by default as identity,
    version bigint not null,
    description varchar(255) not null,
    primary key (id)
);

create table state (
    id bigint generated by default as identity,
    version bigint not null,
    abbrev varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table type (
    id bigint generated by default as identity,
    version bigint not null,
    description varchar(255) not null,
    primary key (id)
);

alter table address
    add constraint FK_gsutw0t9tnbyjepppx6e2473t
    foreign key (state_id)
    references state;

alter table appointment
    add constraint FK_bdb382stfie0n7687tjxau9w1
    foreign key (firm_id)
    references firm;

alter table appointment
    add constraint FK_opiiek6nch00kt8rhofljjxqm
    foreign key (organizer_id)
    references employee;

alter table business_entity
    add constraint FK_nba7s6hwhfq1nep202goldr22
    foreign key (address_id)
    references address;

alter table client
    add constraint FK_7xlu3sl4us5nxhdt0rty5otf8
    foreign key (id)
    references person;

alter table contact
    add constraint FK_9b33oaood729db3kfmv9g7kca
    foreign key (client_id)
    references client;

alter table contact
    add constraint FK_eq8knrcsm7tmqdnyytnvo8hha
    foreign key (legal_case_id)
    references legal_case;

alter table contact
    add constraint FK_6tnxpisy05swbp7l3pld0a5a1
    foreign key (id)
    references person;

alter table daily_log_entry
    add constraint FK_93s7qx3d19ws3nxt39h92oqdf
    foreign key (employee_id)
    references employee;

alter table daily_log_entry
    add constraint FK_k8t73eh30h6mev8o0wj956lde
    foreign key (legal_case_id)
    references legal_case;

alter table email_address
    add constraint FK_jjgbyibkkcfvai4w5xkq9gymv
    foreign key (owner_id)
    references business_entity;

alter table email_address
    add constraint FK_in2scx8da934u9enag5nq03wo
    foreign key (type_id)
    references type;

alter table employee
    add constraint FK_nhli7owi6ferubmgll5umph0
    foreign key (id)
    references person;

alter table firm
    add constraint FK_pmrm50h022k4bqortocv26nrg
    foreign key (id)
    references business_entity;

alter table lawyer
    add constraint FK_pyf4g3mfdng5arb4g6omd0xp2
    foreign key (id)
    references person;

alter table lawyer_specialty
    add constraint FK_40jmcl04v4ice619vwej58icw
    foreign key (lawyer_id)
    references lawyer;

alter table lawyer_specialty
    add constraint FK_c3x9fn2hqfd9r50sb4fof1po2
    foreign key (specialty_id)
    references specialty;

alter table legal_case
    add constraint FK_8ljy0smtlsuvkaldvchbtm73i
    foreign key (client_id)
    references client;

alter table legal_case
    add constraint FK_3lar6i5uag2mjicyfsqlxw29u
    foreign key (primary_lawyer_id)
    references lawyer;

alter table legal_case_employee
    add constraint FK_fmku2dbqfho4rs1f1gwvjgsg4
    foreign key (legal_case_id)
    references legal_case;

alter table legal_case_employee
    add constraint FK_btbwuvy6mmgc3hmv1fi6kp038
    foreign key (employee_id)
    references employee;

alter table person
    add constraint FK_4ht90pj9rj91hj3dqhx5c40ut
    foreign key (id)
    references business_entity;

alter table person_appointment
    add constraint FK_cpi40yg8hecfy6tq52hjdium0
    foreign key (person_id)
    references person;

alter table person_appointment
    add constraint FK_afixl5xlqtcm8ny4yb51wyysf
    foreign key (appointment_id)
    references appointment;

alter table phone_number
    add constraint FK_tqs5t32vx23hq4xobgjl317al
    foreign key (owner_id)
    references business_entity;

alter table phone_number
    add constraint FK_h938873i9d1dlhcto5u7ox9yp
    foreign key (type_id)
    references type;
